// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm8afgznH0bHF7QHCOUnmP1KE7nIDxtlI',
    appId: '1:539407331155:web:e35fb2962590b6a3c2fba6',
    messagingSenderId: '539407331155',
    projectId: 'jaradalab',
    authDomain: 'jaradalab.firebaseapp.com',
    storageBucket: 'jaradalab.appspot.com',
    measurementId: 'G-SQNWJQLJTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBco67l2ORX1HoT2EHvcYZ4Mv45Ef9Igh8',
    appId: '1:539407331155:android:9dc0e94382a871d3c2fba6',
    messagingSenderId: '539407331155',
    projectId: 'jaradalab',
    storageBucket: 'jaradalab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFkU4D8ymJVpKcNkrM9sPGXze9Agelj5c',
    appId: '1:539407331155:ios:bd5072912a1bece0c2fba6',
    messagingSenderId: '539407331155',
    projectId: 'jaradalab',
    storageBucket: 'jaradalab.appspot.com',
    iosClientId: '539407331155-mqkvk0f0192113kdj3i6r48ie1ou35fn.apps.googleusercontent.com',
    iosBundleId: 'com.lab.Jaradalab',
  );
}
